openapi: 3.0.0
x-stoplight:
  id: 50ww96c24qa8n
info:
  title: DoctorApp
  version: '1.0'
  license:
    name: TBD
servers:
  - url: 'http://localhost:3000/v1'
paths:
  '/doctors/{doctorId}/schedules':
    parameters:
      - schema:
          type: string
        name: doctorId
        in: path
        required: true
    get:
      summary: Get schedule for doctor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    required:
                      - objectCount
                      - objectArray
                    properties:
                      objectCount:
                        type: integer
                      objectArray:
                        type: array
                        items:
                          $ref: ../models/schedule.yaml
                required:
                  - statusCode
                  - message
                  - data
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-doctors-doctorId-schedules
      parameters: []
  '/patients/{patientId}/medicalFiles':
    parameters:
      - schema:
          type: string
        name: patientId
        in: path
        required: true
    get:
      summary: Get medical file for patient
      tags: []
      operationId: get-patients-patientId-medicalFiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: ../models/medicalFile.yaml
                required:
                  - statusCode
                  - message
                  - data
              examples: {}
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  '/doctors/{doctorId}/appointmentSummaries':
    parameters:
      - schema:
          type: string
        name: doctorId
        in: path
        required: true
    get:
      summary: Get appointment summary for doctor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    required:
                      - objectCount
                      - hasMore
                      - objectArray
                    properties:
                      objectCount:
                        type: string
                      hasMore:
                        type: string
                      objectArray:
                        type: array
                        items:
                          $ref: ../models/doctorAppointmentSummary.yaml
                required:
                  - statusCode
                  - message
                  - data
              examples:
                Example 1:
                  value:
                    statusCode: string
                    message: string
                    data:
                      objectCount: string
                      hasMore: string
                      objectArray:
                        - medicalCenterId: MC-sdfdsds
                          medicalCenterName: Health Center name
                          expectedVisits:
                            - date: '2019-08-24'
                              morningSlot: 0
                              afternoonSlot: 0
                              eveningSlot: 1
                            - date: '2019-08-25'
                              morningSlot: 0
                              afternoonSlot: 3
                              eveningSlot: 4
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-doctors-doctorId-appointmentSummaries
      parameters: []
  '/doctors/{doctorId}/appointments':
    parameters:
      - schema:
          type: string
        name: doctorId
        in: path
        required: true
    get:
      summary: Get appointment list for doctor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    required:
                      - objectCounter
                      - hasMore
                      - objectArray
                    properties:
                      objectCounter:
                        type: integer
                      hasMore:
                        type: boolean
                      objectArray:
                        type: array
                        items:
                          $ref: ../models/appointment.yaml
                required:
                  - statusCode
                  - message
                  - data
      operationId: get-doctors-doctorId-appointments
      parameters:
        - $ref: ./Main Document.yaml#/components/parameters/limit
        - $ref: ./Main Document.yaml#/components/parameters/starting_after_object
        - schema:
            type: string
          in: query
          name: medicalCenterId
          required: true
          description: medical center ID
        - schema:
            type: string
            format: date
          in: query
          required: true
          name: date
          description: appointment date (format yyyy-mm-dd)
        - schema:
            type: string
          in: query
          name: timeSlot
          required: true
          description: appointment time slot
components:
  schemas: {}
